[Writable]
    LogLevel = 'DEBUG'

[Service]
    BootTimeout = 30000
    ClientMonitor = 15000
    CheckInterval = '10s'
    Host = 'app-filter-mind'
    Port = 48095
    Protocol = 'http'
    ReadMaxLimit = 100
    StartupMsg = 'This is a Filter/MindSphere Application Service'
    Timeout = 5000

[Registry]
    Host = 'edgex-core-consul'
    Port = 8500
    Type = 'consul'

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 48080

[MessageBus]
    Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
    EnableRemote = false
    File = '/edgex/logs/app-filter-mind.log'

# [Binding]
#  Type="messagebus"
#  SubscribeTopic="events"
#  PublishTopic="somewhere"
 
#[Binding]
#Type="http"

[ApplicationSettings]
    ApplicationName = "app-filter-mind"
    RulePort = "48096"
